Landing page
MICHAELKITH/review-code pull request #1
Opened 2022-12-12 15:53 UTC by MICHAELKITH

#what 

1. added index.html file 
2. added style.css file

2022-12-12 16:20 UTC, MICHAELKITH reviewed
### Changes Required ♻️ 

 Please check all my comments below and make required changes 

Submit for re-review when done 😀 

Thanks 😄 

### Highlights 

1. Descriptive README file ✔️👨🏻‍💻

2.No GitHub Flow. ❌ 

3. Linter errors.  : ❌

2022-12-12 16:20 UTC, MICHAELKITH commented on index.html
> +      </ul>
You did a great job 😀 but kindly implement use of <li> tags 👍

2022-12-12 17:06 UTC, Lizdev-05 requested changes
Hi @MICHAELKITH, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<img src="https://media3.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>
## Highlights
- Polite tone was used ✅
## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
- I think it will be nice if you make use of gifs and emojis, this will make your code review appear humanly friendly 😎☺️
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-12 17:06 UTC, Lizdev-05 commented on index.html
> +      </ul>
Great job commending the programmer and pointing out the error 👍. I think it will be great if you tell the reviewer why you are requesting the changes. This will make the programmer know why the changes are necessary and will prevent them from making the same error next time. 😊🟢

2022-12-13 03:12 UTC, binhussen approved these changes
Hi @MICHAELKITH , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉
<img src="https://user-images.githubusercontent.com/65852621/133696182-6c5b784b-0083-427a-b24d-3ec870915f79.jpg"/>
## Highlights
- All linter checks passed ✔️
- Descriptive pull request ✔️
- Used GitHub flow ✔️
## Optional suggestions
- [Optionnal] Good job for your comment 👍  I think it is better to Add as many inline comments as possible as the [project requirements](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/code-review/review_your_project.md) 

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-16 08:46 UTC, merged